{
  "api": "search",
  "file": "/test/free/data_stream/190_failure_store_redirection.yml",
  "name": "Redirect ingest failure in data stream to failure store",
  "origin": "yaml",
  "request": {
    "args": {
      "index": ".fs-logs-foobar-*",
      "typed_keys": true
    }
  },
  "response": {
    "headers": {
      "content-type": "application/json",
      "transfer-encoding": "chunked",
      "x-elastic-product": "Elasticsearch"
    },
    "payload": {
      "_shards": {
        "failed": 0,
        "skipped": 0,
        "successful": 1,
        "total": 1
      },
      "hits": {
        "hits": [
          {
            "_id": "5VG3rpkBkI_JdX9OaMJk",
            "_index": ".fs-logs-foobar-2025.10.04-000001",
            "_score": 1,
            "_source": {
              "@timestamp": "2025-10-04T10:14:39.334Z",
              "document": {
                "index": "logs-foobar",
                "source": {
                  "@timestamp": "2020-12-12",
                  "foo": "bar"
                }
              },
              "error": {
                "message": "error_message",
                "pipeline": "failing_pipeline",
                "pipeline_trace": [
                  "parent_failing_pipeline",
                  "failing_pipeline"
                ],
                "processor_tag": "foo-tag",
                "processor_type": "fail",
                "stack_trace": "o.e.i.c.FailProcessorException: error_message\n\tat o.e.i.c.FailProcessor.execute(FailProcessor.java:42)\n\tat o.e.i.CompoundProcessor.innerExecute(CompoundProcessor.java:171)\n\t... 18 more\n",
                "type": "fail_processor_exception"
              }
            }
          }
        ],
        "max_score": 1,
        "total": {
          "relation": "eq",
          "value": 1
        }
      },
      "timed_out": false,
      "took": 0
    },
    "statusCode": 200
  }
}