{
  "api": "ml.start_trained_model_deployment",
  "file": "/test/platinum/ml/3rd_party_deployment.yml",
  "name": "Test stop deployments with allow_no_match",
  "origin": "yaml",
  "request": {
    "args": {
      "deployment_id": "test_model_for_search",
      "model_id": "test_model",
      "wait_for": "started"
    }
  },
  "response": {
    "headers": {
      "content-length": "661",
      "content-type": "application/json",
      "x-elastic-product": "Elasticsearch"
    },
    "payload": {
      "error": {
        "caused_by": {
          "reason": "Could not start deployment because no suitable nodes were found, allocation explanation [Could not assign (more) allocations on node [NDva5I7rSvS899tFq3ZSBQ]. Reason: This node has insufficient allocated processors. Available processors [2], free processors [0], processors required for each allocation of this model [1]]",
          "type": "illegal_state_exception"
        },
        "reason": "Could not start deployment because no ML nodes with sufficient capacity were found",
        "root_cause": [
          {
            "reason": "Could not start deployment because no ML nodes with sufficient capacity were found",
            "type": "status_exception"
          }
        ],
        "type": "status_exception"
      },
      "status": 429
    },
    "statusCode": 429
  }
}