{
  "api": "ml.put_job",
  "file": "/test/platinum/ml/jobs_crud.yml",
  "name": "Test force closing a closed job isn't an error",
  "origin": "yaml",
  "request": {
    "args": {
      "body": {
        "analysis_config": {
          "detectors": [
            {
              "function": "count"
            }
          ]
        },
        "analysis_limits": {
          "model_memory_limit": "20mb"
        },
        "data_description": {
          "format": "xcontent"
        },
        "description": "Analysis of response time by airline"
      },
      "job_id": "jobs-crud-close-a-closed-job"
    }
  },
  "response": {
    "headers": {
      "content-length": "337",
      "content-type": "application/json",
      "x-elastic-product": "Elasticsearch"
    },
    "payload": {
      "error": {
        "reason": "The job cannot be created with the Id 'jobs-crud-close-a-closed-job'. The Id is already used.",
        "root_cause": [
          {
            "reason": "The job cannot be created with the Id 'jobs-crud-close-a-closed-job'. The Id is already used.",
            "type": "resource_already_exists_exception"
          }
        ],
        "type": "resource_already_exists_exception"
      },
      "status": 400
    },
    "statusCode": 400
  }
}