{
  "api": "ml.put_trained_model",
  "file": "/test/platinum/ml/3rd_party_deployment.yml",
  "name": "Test getting and putting Fill Mask with two mask tokens, as well as exceptions caused by requests with the wrong token",
  "origin": "yaml",
  "request": {
    "args": {
      "body": {
        "description": "simple model for testing",
        "inference_config": {
          "fill_mask": {
            "mask_token": "<mask>",
            "tokenization": {
              "roberta": {
                "with_special_tokens": false
              }
            }
          }
        },
        "model_type": "pytorch"
      },
      "model_id": "with_other_correct_mask_token"
    }
  },
  "response": {
    "headers": {
      "content-length": "645",
      "content-type": "application/json",
      "x-elastic-product": "Elasticsearch"
    },
    "payload": {
      "create_time": 1749119471762,
      "created_by": "api_user",
      "description": "simple model for testing",
      "estimated_operations": 0,
      "inference_config": {
        "fill_mask": {
          "mask_token": "<mask>",
          "num_top_classes": 5,
          "tokenization": {
            "roberta": {
              "add_prefix_space": false,
              "do_lower_case": false,
              "max_sequence_length": 512,
              "span": -1,
              "truncate": "first",
              "with_special_tokens": false
            }
          },
          "vocabulary": {
            "index": ".ml-inference-native-000002"
          }
        }
      },
      "input": {
        "field_names": [
          "input"
        ]
      },
      "license_level": "platinum",
      "location": {
        "index": {
          "name": ".ml-inference-native-000002"
        }
      },
      "model_id": "with_other_correct_mask_token",
      "model_size_bytes": 0,
      "model_type": "pytorch",
      "tags": [
      ],
      "version": "12.0.0"
    },
    "statusCode": 200
  }
}